### ISSUE TITLE
Request for dedicated model sampling script to use after training

### ISSUE THREAD

**Issue by GenTxt** [Shivanandroy/T5-Finetuning-PyTorch#1]
Thanks for this great T5 repo. Everything is working 100% and I've managed to generate a few custom models with impressive results in the 'predictions.csv' files.

I've run the models through the default transformers 'run_summarization.py' using  --do_predict --predict_with_generate  but the results are bad compared to the superior results in your  'predictions.csv' output.

I've converted the notebook to a python script and tried editing but I can't get it to run because of the use of 'rich'

Could you suggest modifications to your code or provide a simple script that would allow for the generation of a 'predictions.csv' from a finetuned model after training is completed? 

Thanks

**Comment by Shivanandroy** [comment]
You can use simpleT5 : https://github.com/Shivanandroy/simpleT5

**Comment by Shivanandroy** [comment]
Feel free to open, in case the issue is not resolved
